name: DiscordLink
version: 2.2.3
author: KarateMan2400
main: com.karateman.discordlink.DiscordLinkPlugin
softdepend: [PlaceholderAPI]
commands:
  verify:
    description: Verify yourself with Discord!
  unverify:
    description: Unverify yourself from Discord!
  discordlink:
    description: Main plugin command